import Head from "next/head";
import NavBar from "../components/NavBar";
// import Main from "../components/layouts/Main";
import Image from "next/image";
import bgHome from "/public/images/bgHome.jpg";
import Service from "../components/Service";
// import Drawer from "../components/Drawer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-to-b  from-green-700 to to-yellow-100 ">
        <div className="">
          <div className="h-screen">
            <div className="relative overflow-hidden h-full ">
              <NavBar />
              <Image
                alt=""
                objectFit="cover"
                layout="fill"
                src={bgHome}
                className=" relative brightness-50 "
              />
              <h1 className="text-white top-1/2 text-center w-full absolute text-5xl md:text-8xl font-bold">
                GABUH
                <p className="absolute text-white text-center w-full text-base md:text-3xl mt-3">
                  Travel & Tours
                </p>
              </h1>
              <div className="9xl text-white">Hey</div>
            </div>
          </div>

          <div className="">
            <Service />
          </div>
        </div>
      </main>

      {/* <Drawer  /> */}
    </>
  );
}
