import Head from "next/head";
import NavBar from "../components/NavBar";
// import Main from "../components/layouts/Main";
import Image from "next/image";
import bgHome from "/public/images/bgHome.jpg";
// import Drawer from "../components/Drawer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-to-b from-green-700 to to-yellow-100 h-screen overflow-y-scroll">
        <NavBar />
        <div className=" max-w-7xl mx-auto mt-7 px-2">
          <div className="relative overflow-hidden h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600] 2xl:h-[700]">
            <Image
              alt=""
              objectFit="cover"
              layout="fill"
             
              src={bgHome}
              className="rounded-3xl relative brightness-50 "
            />
            <h1 className="text-white top-1/2 text-center w-full absolute text-5xl md:text-8xl font-bold">
              GABUH
              <p className="absolute text-white text-center w-full text-base md:text-3xl mt-3">
                Travel & Tours
                
              </p>
              
            </h1>
            
          </div>

          <h1 className="text-justify">
            
          </h1>
        </div>

        <div className="max-w-7xl mx-auto"></div>
      </main>

      {/* <Drawer  /> */}
    </>
  );
}
