import Head from "next/head";
import NavBar from "../components/NavBar";
// import Main from "../components/layouts/Main";
import Image from "next/image";
import bgHome from "/public/images/bgHome.jpg";
import logoCo from "/public/images/logoCo.jpeg";
import Service from "../components/Service";
import About from "../components/About";
// import Drawer from "../components/Drawer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white ">
        <div className="">
          <div className="h-screen">
            <div className="relative overflow-hidden h-full ">
              <NavBar />
              <Image
                alt=""
                objectFit="cover"
                layout="fill"
                src={bgHome}
                className=" relative brightness-50 "
              />
              <div className="w-full top-20 text-center absolute">
                <Image
                  alt=""
                  objectFit="cover"
                  layout="fixed"
                  height={100}
                  width={100}
                  src={logoCo}
                  className="rounded-full shadow"
                />
              </div>
              <h1 className="text-white top-1/2 text-center w-full absolute text-5xl md:text-8xl font-bold">
                GABUH Travel & Tours
                <p className="absolute text-white text-center w-full text-base md:text-3xl mt-3">
                  We Bring only Best Tours
                </p>
              </h1>
              <div className="absolute bottom-10 md:bottom-40 text-center w-full  ">
                <button className=" btn glass w-fit text-white font-bold text-lg ">
                  Book with Us
                </button>
              </div>
            </div>
          </div>
          <div>
            <About />
          </div>
          <div className="">
            <Service />
          </div>
          <div></div>
        </div>
      </main>

      {/* <Drawer  /> */}
    </>
  );
}
